<?php

const DB_HOST = '';

const DB_USER = '';

const DB_PASS = '';

const DB_NAME = '';



const USER_CREATED = 101;
const USER_EXISTS = 102;
const USER_FAILURE = 103;
const EMAIL_EXISTS = 105;
const NURSE_UPDATED = 106;
const NURSE_FAILURE = 107;
const ADMIN_UPDATED = 108;
const ADMIN_FAILURE = 109;

const SHIFT_CREATED = 104;
const SHIFT_CONFLICTS = 105;
const SHIFT_FAILURE = 106;

const REQUEST_CREATED = 107;
const REQUEST_EXISTS = 108;
const REQUEST_FAILURE = 109;

const USER_AUTH = 201;
const USER_NOT_FOUND = 202;
const USER_NOT_AUTH = 203;

const PASSWORD_UPDATED = 301;
const PASSWORD_INVALID = 302;
const PASSWORD_NOT_UPDATED = 303;

const USERNAME_EXISTS = 104;
const USERNAME_UPDATED = 304;
const USERNAME_INVALID = 305;
const USERNAME_NOT_UPDATED = 306;
